# This module is not autogenerated, this was created to move authentication logic out of the model
module Authenticable
  extend ActiveSupport::Concern

  included do
    has_secure_password
    has_many :sessions, dependent: :destroy

    normalizes :email_address, with: ->(e) { e.strip.downcase }
  end
end
